(() => {
'use strict';
const $=id=>document.getElementById(id), canvas=$('gameCanvas'),ctx=canvas.getContext('2d');
const ui={food:$('food'),power:$('power'),scrap:$('scrap'),population:$('population'),morale:$('morale'),moraleBar:$('moraleBar'),phaseLabel:$('phaseLabel'),phaseTimer:$('phaseTimer'),phaseDot:$('phaseDot'),hqHealth:$('hqHealth'),enemyCount:$('enemyCount'),pauseBtn:$('pauseBtn'),speedBtn:$('speedBtn'),buildRail:$('buildRail'),selectionLabel:$('selectionLabel'),clearSelection:$('clearSelection'),inspectMode:$('inspectMode'),toast:$('toast'),eventModal:$('eventModal'),eventIcon:$('eventIcon'),eventTitle:$('eventTitle'),eventText:$('eventText'),eventChoices:$('eventChoices'),inspectModal:$('inspectModal'),inspectName:$('inspectName'),inspectLevel:$('inspectLevel'),inspectHealth:$('inspectHealth'),inspectOutput:$('inspectOutput'),inspectDescription:$('inspectDescription'),upgradeBtn:$('upgradeBtn'),demolishBtn:$('demolishBtn'),closeInspect:$('closeInspect'),gameOverModal:$('gameOverModal'),gameOverTitle:$('gameOverTitle'),gameOverStats:$('gameOverStats'),restartBtn:$('restartBtn')};
const G={cols:9,rows:11}, DAY=45,NIGHT=38,SAVE='last-city-save-v4';
const defs={
 farm:{n:'Hydro Farm',e:'🌱',cost:30,crew:2,hp:100,food:7,desc:'Produces food every day.'},
 solar:{n:'Solar Array',e:'☀️',cost:34,crew:2,hp:90,power:9,desc:'Produces power during daylight.'},
 recycler:{n:'Recycler',e:'♻️',cost:44,crew:3,hp:110,scrap:5,desc:'Recovers useful scrap.'},
 shelter:{n:'Shelter',e:'🏠',cost:48,crew:0,hp:125,pop:5,desc:'Increases survivor capacity.'},
 tower:{n:'Guard Tower',e:'🛡️',cost:56,crew:3,hp:125,range:3.2,dmg:13,rate:.7,desc:'Automatic night defense.'},
 tesla:{n:'Tesla Coil',e:'⚡',cost:84,crew:4,hp:100,range:2.8,dmg:21,rate:1.05,desc:'High damage electric defense.'},
 clinic:{n:'Clinic',e:'🏥',cost:70,crew:3,hp:105,heal:3,desc:'Repairs nearby structures.'},
 wall:{n:'Barricade',e:'🧱',cost:22,crew:0,hp:230,desc:'Cheap durable barrier.'},
 hq:{n:'City Core',e:'🏛️',cost:0,crew:0,hp:420,desc:'If it falls, the city is lost.'}
};
const enemyDefs={crawler:{hp:36,spd:.55,dmg:8,r:.18,c:'#ff7b72'},brute:{hp:95,spd:.34,dmg:16,r:.25,c:'#d97757'},runner:{hp:28,spd:.82,dmg:6,r:.16,c:'#ffb45d'},spitter:{hp:54,spd:.42,dmg:10,r:.19,c:'#be7cff'},titan:{hp:520,spd:.22,dmg:30,r:.36,c:'#ff4d67'}};
let uid=1,layout={},last=performance.now(),toastT=0;
function fresh(){return {day:1,phase:'day',time:DAY,food:78,power:70,scrap:135,pop:12,morale:72,score:0,kills:0,paused:false,speed:1,selected:null,inspect:false,inspected:null,buildings:[mk('hq',4,5)],enemies:[],shots:[],particles:[],spawnClock:0,eventOpen:false,gameOver:false};}
function mk(type,x,y){const d=defs[type];return{id:uid++,type,x,y,level:1,hp:d.hp,maxHp:d.hp,cd:0};}
let state=load()||fresh();
function load(){try{const v=JSON.parse(localStorage.getItem(SAVE));if(!v||!v.buildings)return null;uid=Math.max(1,...v.buildings.map(b=>b.id||0))+1;return Object.assign(fresh(),v,{paused:false,eventOpen:false,gameOver:false,enemies:[],shots:[],particles:[]});}catch{return null}}
function save(){if(!state.gameOver)localStorage.setItem(SAVE,JSON.stringify({...state,enemies:[],shots:[],particles:[],paused:false,eventOpen:false}));}
function haptic(n=8){try{navigator.vibrate?.(n)}catch{}}
function toast(t,bad=false){ui.toast.textContent=t;ui.toast.style.borderColor=bad?'rgba(255,111,120,.4)':'';ui.toast.classList.add('show');clearTimeout(toastT);toastT=setTimeout(()=>ui.toast.classList.remove('show'),1500)}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0);const cell=Math.min(r.width/G.cols,r.height/G.rows);layout={w:r.width,h:r.height,cell,ox:(r.width-cell*G.cols)/2,oy:(r.height-cell*G.rows)/2};}
function buildingAt(x,y){return state.buildings.find(b=>b.x===x&&b.y===y)}
function availCrew(){const used=state.buildings.reduce((a,b)=>a+(defs[b.type].crew||0)*b.level,0);return Math.max(0,state.pop-used)}
function cardRail(){ui.buildRail.innerHTML='';Object.entries(defs).filter(([k])=>k!=='hq').forEach(([k,d])=>{const b=document.createElement('button');b.className='build-card';b.dataset.t=k;b.innerHTML=`<span class="emoji">${d.e}</span><b>${d.n}</b><small>${d.crew?d.crew+' crew':'no crew'}</small><span class="cost-badge">🔩 ${d.cost}</span>`;b.onclick=()=>{state.selected=state.selected===k?null:k;state.inspect=false;selection();haptic()};ui.buildRail.appendChild(b)});selection()}
function selection(){document.querySelectorAll('.build-card').forEach(b=>b.classList.toggle('selected',b.dataset.t===state.selected));ui.selectionLabel.textContent=state.selected?defs[state.selected].n:'Choose a structure';ui.inspectMode.classList.toggle('active',state.inspect)}
function place(type,x,y){const d=defs[type];if(state.phase!=='day')return toast('Build during daylight',true);if(buildingAt(x,y))return toast('Tile occupied',true);if(state.scrap<d.cost)return toast('Not enough scrap',true);if(availCrew()<d.crew)return toast('Not enough free crew',true);state.scrap-=d.cost;state.buildings.push(mk(type,x,y));state.score+=d.cost;haptic(12);toast(`${d.n} constructed`);save()}
function upgrade(id){const b=state.buildings.find(x=>x.id===id);if(!b||b.type==='hq'||b.level>=4)return;const cost=Math.round(defs[b.type].cost*(.65+.3*b.level));if(state.scrap<cost)return toast('Not enough scrap',true);if(availCrew()<defs[b.type].crew)return toast('Need more free crew',true);state.scrap-=cost;b.level++;b.maxHp=Math.round(defs[b.type].hp*(1+.38*(b.level-1)));b.hp=b.maxHp;openInspect(id);save();haptic(15)}
function demolish(id){const i=state.buildings.findIndex(x=>x.id===id);if(i<0||state.buildings[i].type==='hq')return;const b=state.buildings[i];state.scrap+=Math.round(defs[b.type].cost*.4*b.level);state.buildings.splice(i,1);closeInspect();save();toast('Structure dismantled')}
function openInspect(id){const b=state.buildings.find(x=>x.id===id);if(!b)return;state.inspected=id;const d=defs[b.type];ui.inspectName.textContent=d.n;ui.inspectLevel.textContent=b.level;ui.inspectHealth.textContent=`${Math.round(100*b.hp/b.maxHp)}%`;ui.inspectDescription.textContent=d.desc;ui.inspectOutput.textContent=d.food?`+${d.food*b.level} food`:d.power?`+${d.power*b.level} power`:d.scrap?`+${d.scrap*b.level} scrap`:d.pop?`+${d.pop*b.level} cap`:d.dmg?`${Math.round(d.dmg*(1+.35*(b.level-1)))} dmg`:'Defense';ui.upgradeBtn.style.display=b.type==='hq'?'none':'';ui.demolishBtn.style.display=b.type==='hq'?'none':'';if(b.type!=='hq')ui.upgradeBtn.textContent=`Upgrade · 🔩 ${Math.round(d.cost*(.65+.3*b.level))}`;ui.inspectModal.classList.remove('hidden')}
function closeInspect(){state.inspected=null;ui.inspectModal.classList.add('hidden')}
function startNight(){state.phase='night';state.time=NIGHT;state.spawnClock=.2;state.selected=null;selection();toast(`Night ${state.day} — defend the Core!`);haptic(25)}
function startDay(){state.day++;state.phase='day';state.time=DAY;const mult=1+Math.floor((state.day-1)/4)*.05;for(const b of state.buildings){const d=defs[b.type],lv=b.level;state.food+=(d.food||0)*lv*mult;state.power+=(d.power||0)*lv*mult;state.scrap+=(d.scrap||0)*lv*mult;if(d.heal){for(const x of state.buildings)x.hp=Math.min(x.maxHp,x.hp+d.heal*lv*4)}}const cap=12+state.buildings.reduce((a,b)=>a+(defs[b.type].pop||0)*b.level,0);state.pop=Math.min(cap,state.pop+1);const need=Math.max(5,Math.round(state.pop*.65));if(state.food>=need){state.food-=need;state.morale=Math.min(100,state.morale+3)}else{state.food=0;state.morale=Math.max(0,state.morale-14);state.pop=Math.max(1,state.pop-1);toast('Food shortage — survivor lost',true)}state.scrap+=8+state.day*2;state.score+=state.day*20;save();if(state.day%3===0)setTimeout(eventPopup,450);else toast(`Dawn ${state.day} — rebuild and prepare`)}
function spawn(){const boss=state.day%5===0&&!state.enemies.some(e=>e.type==='titan')&&state.time<NIGHT*.65;let type=boss?'titan':(['crawler','crawler','runner',state.day>2?'brute':'crawler',state.day>3?'spitter':'runner'][Math.floor(Math.random()*5)]);const d=enemyDefs[type],edge=Math.floor(Math.random()*4);let x=edge===0?-.3:edge===1?G.cols-.7:Math.random()*(G.cols-1),y=edge===2?-.3:edge===3?G.rows-.7:Math.random()*(G.rows-1);const scale=1+(state.day-1)*.1;state.enemies.push({id:uid++,type,x,y,hp:d.hp*scale,maxHp:d.hp*scale,atk:0});}
function targetFor(e){let best=null,bd=1e9;for(const b of state.buildings){const d=Math.hypot((b.x+.5)-e.x,(b.y+.5)-e.y);if(d<bd){bd=d;best=b}}return [best,bd]}
function enemyTick(dt){state.spawnClock-=dt;if(state.spawnClock<=0&&state.time>2){spawn();state.spawnClock=Math.max(.48,1.75-state.day*.07)}for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i],d=enemyDefs[e.type],[t,dist]=targetFor(e);if(!t)continue;if(dist<.45){e.atk-=dt;if(e.atk<=0){t.hp-=d.dmg*(1+state.day*.035);e.atk=1.1;if(t.hp<=0){if(t.type==='hq')return gameOver();state.buildings=state.buildings.filter(b=>b.id!==t.id);toast(`${defs[t.type].n} destroyed`,true)}}}else{e.x+=((t.x+.5-e.x)/dist)*d.spd*dt;e.y+=((t.y+.5-e.y)/dist)*d.spd*dt}if(e.hp<=0){state.kills++;state.scrap+=e.type==='titan'?45:2+Math.floor(Math.random()*3);state.score+=e.type==='titan'?250:12;burst(e.x,e.y,d.c);state.enemies.splice(i,1)}}}
function defenseTick(dt){for(const b of state.buildings){const d=defs[b.type];if(!d.dmg)continue;b.cd=(b.cd||0)-dt;if(b.cd>0)continue;const r=(d.range||0)+(b.level-1)*.25;let best=null,bd=r;for(const e of state.enemies){const q=Math.hypot(e.x-(b.x+.5),e.y-(b.y+.5));if(q<bd){bd=q;best=e}}if(best&&state.power>=.35){state.power=Math.max(0,state.power-.35);const dmg=d.dmg*(1+.35*(b.level-1));state.shots.push({x:b.x+.5,y:b.y+.5,tx:best.x,ty:best.y,t:.14,c:b.type==='tesla'?'#73b8ff':'#ffcd6b'});best.hp-=dmg;b.cd=d.rate/(1+.12*(b.level-1))}}}
function burst(x,y,c){for(let i=0;i<8;i++)state.particles.push({x,y,vx:(Math.random()-.5)*1.3,vy:(Math.random()-.5)*1.3,life:.6,c})}
function fx(dt){for(const s of state.shots)s.t-=dt;state.shots=state.shots.filter(s=>s.t>0);for(const p of state.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt}state.particles=state.particles.filter(p=>p.life>0)}
const events=[
 {i:'🚪',t:'Refugees at the gate',x:'A tired group asks to join the city.',a:[['Take them in','+3 survivors, -12 food',()=>{state.pop+=3;state.food=Math.max(0,state.food-12);state.morale+=4}],['Give supplies','-10 food, +8 morale',()=>{state.food=Math.max(0,state.food-10);state.morale+=8}],['Turn them away','No cost, -5 morale',()=>state.morale-=5]]},
 {i:'📦',t:'Abandoned convoy',x:'Scouts find sealed cargo outside the perimeter.',a:[['Recover scrap','+32 scrap',()=>state.scrap+=32],['Take batteries','+28 power',()=>state.power+=28],['Take rations','+25 food',()=>state.food+=25]]},
 {i:'⚠️',t:'Generator overload',x:'The grid is unstable. Shut it down or risk damage.',a:[['Safe shutdown','-12 power',()=>state.power=Math.max(0,state.power-12)],['Push through','+15 scrap, random damage',()=>{state.scrap+=15;const b=state.buildings[Math.floor(Math.random()*state.buildings.length)];b.hp=Math.max(1,b.hp-35)}]]}
];
function eventPopup(){if(state.eventOpen||state.gameOver)return;state.eventOpen=true;const e=events[Math.floor(Math.random()*events.length)];ui.eventIcon.textContent=e.i;ui.eventTitle.textContent=e.t;ui.eventText.textContent=e.x;ui.eventChoices.innerHTML='';e.a.forEach(([a,b,fn])=>{const bt=document.createElement('button');bt.className='choice-btn';bt.innerHTML=`<b>${a}</b><small>${b}</small>`;bt.onclick=()=>{fn();state.morale=Math.max(0,Math.min(100,state.morale));state.eventOpen=false;ui.eventModal.classList.add('hidden');save();haptic(12)};ui.eventChoices.appendChild(bt)});ui.eventModal.classList.remove('hidden')}
function gameOver(){state.gameOver=true;state.paused=true;localStorage.removeItem(SAVE);ui.gameOverTitle.textContent=`Survived ${state.day} days`;ui.gameOverStats.textContent=`Score ${Math.round(state.score)} · ${state.kills} enemies defeated`;ui.gameOverModal.classList.remove('hidden');haptic(80)}
function reset(){localStorage.removeItem(SAVE);state=fresh();ui.gameOverModal.classList.add('hidden');cardRail();save()}
function update(dt){if(state.paused||state.eventOpen||state.gameOver)return;dt*=state.speed;state.time-=dt;if(state.phase==='night'){enemyTick(dt);defenseTick(dt)}fx(dt);if(state.time<=0){if(state.phase==='day')startNight();else if(state.enemies.length===0)startDay();else state.time=0}if(state.phase==='night'&&state.time===0&&state.enemies.length===0)startDay()}
function hud(){ui.food.textContent=Math.floor(state.food);ui.power.textContent=Math.floor(state.power);ui.scrap.textContent=Math.floor(state.scrap);ui.population.textContent=`${state.pop}`;ui.morale.textContent=`${Math.round(state.morale)}%`;ui.moraleBar.style.width=`${Math.max(0,state.morale)}%`;ui.phaseLabel.textContent=`${state.phase.toUpperCase()} ${state.day}`;ui.phaseTimer.textContent=`00:${String(Math.ceil(state.time)).padStart(2,'0')}`;ui.phaseDot.style.background=state.phase==='day'?'#ffcd6b':'#73b8ff';const hq=state.buildings.find(b=>b.type==='hq');ui.hqHealth.textContent=hq?`${Math.max(0,Math.round(100*hq.hp/hq.maxHp))}%`:'0%';ui.enemyCount.textContent=state.enemies.length;ui.pauseBtn.textContent=state.paused?'▶':'Ⅱ';ui.speedBtn.textContent=`${state.speed}×`}
function p2c(x,y){return{x:layout.ox+x*layout.cell,y:layout.oy+y*layout.cell}}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function draw(){const {w,h,cell,ox,oy}=layout;if(!w)return;ctx.clearRect(0,0,w,h);const bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,state.phase==='night'?'#07101b':'#18241f');bg.addColorStop(1,'#08110f');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);for(let y=0;y<G.rows;y++)for(let x=0;x<G.cols;x++){ctx.fillStyle=`rgba(110,145,130,${.055+((x*7+y*11)%5)*.008})`;roundRect(ox+x*cell+1.5,oy+y*cell+1.5,cell-3,cell-3,Math.max(4,cell*.1));ctx.fill()}for(const b of state.buildings){const c=p2c(b.x+.5,b.y+.5),d=defs[b.type],s=cell*(b.type==='hq'?.76:.64);ctx.fillStyle=b.type==='hq'?'#173f3c':b.type==='wall'?'#383e3b':'#1c302b';ctx.strokeStyle=b.type==='hq'?'#4f8e87':'rgba(255,255,255,.12)';roundRect(c.x-s/2,c.y-s/2,s,s,s*.18);ctx.fill();ctx.stroke();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${Math.max(16,cell*.36)}px sans-serif`;ctx.fillText(d.e,c.x,c.y);if(b.hp<b.maxHp){ctx.fillStyle='#1a1a1a';ctx.fillRect(c.x-s*.38,c.y+s*.42,s*.76,3);ctx.fillStyle=b.hp/b.maxHp>.4?'#70f0b0':'#ff6f78';ctx.fillRect(c.x-s*.38,c.y+s*.42,s*.76*Math.max(0,b.hp/b.maxHp),3)}}for(const e of state.enemies){const p=p2c(e.x,e.y),d=enemyDefs[e.type],r=cell*d.r;ctx.shadowColor=d.c;ctx.shadowBlur=8;ctx.fillStyle=d.c;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(e.hp<e.maxHp){ctx.fillStyle='#111';ctx.fillRect(p.x-r,p.y-r-5,r*2,3);ctx.fillStyle='#ff8a7e';ctx.fillRect(p.x-r,p.y-r-5,r*2*Math.max(0,e.hp/e.maxHp),3)}}for(const s of state.shots){const a=p2c(s.x,s.y),b=p2c(s.tx,s.ty);ctx.strokeStyle=s.c;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(const p of state.particles){const q=p2c(p.x,p.y);ctx.globalAlpha=Math.max(0,p.life/.6);ctx.fillStyle=p.c;ctx.fillRect(q.x,q.y,3,3);ctx.globalAlpha=1}}
function cellFrom(ev){const r=canvas.getBoundingClientRect(),x=(ev.clientX-r.left-layout.ox)/layout.cell,y=(ev.clientY-r.top-layout.oy)/layout.cell,ix=Math.floor(x),iy=Math.floor(y);return ix>=0&&iy>=0&&ix<G.cols&&iy<G.rows?{x:ix,y:iy}:null}
canvas.addEventListener('pointerdown',ev=>{if(state.eventOpen||state.gameOver)return;const c=cellFrom(ev);if(!c)return;const b=buildingAt(c.x,c.y);if(state.inspect||!state.selected){if(b)openInspect(b.id);else if(state.inspect)toast('No structure on that tile');return}place(state.selected,c.x,c.y)});
ui.pauseBtn.onclick=()=>{state.paused=!state.paused;hud();haptic()};ui.speedBtn.onclick=()=>{state.speed=state.speed===1?2:1;hud();haptic()};ui.inspectMode.onclick=()=>{state.inspect=!state.inspect;state.selected=null;selection()};ui.clearSelection.onclick=()=>{state.selected=null;state.inspect=false;selection()};ui.closeInspect.onclick=closeInspect;ui.inspectModal.onclick=e=>{if(e.target===ui.inspectModal)closeInspect()};ui.upgradeBtn.onclick=()=>upgrade(state.inspected);ui.demolishBtn.onclick=()=>demolish(state.inspected);ui.restartBtn.onclick=reset;
addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});addEventListener('beforeunload',save);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
function frame(t){const dt=Math.min(.05,(t-last)/1000||0);last=t;update(dt);draw();hud();requestAnimationFrame(frame)}resize();cardRail();hud();requestAnimationFrame(frame);setTimeout(()=>toast('Build food, power & defenses before nightfall'),500);
})();
